name: Debug Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: build
        run: |
          rm -f temporal-src-network.zip && \
          (cd src; zip -r ../temporal-src-network.zip *)

      - name: sha256sums
        run: |
          sha256sum temporal-src-network.zip > sha256sums.txt

      - name: Attach temporal-src-network file
        uses: actions/upload-artifact@v3
        with:
          name: temporal-src-network-build
          path: |
            temporal-src-network.zip
            sha256sums.txt
