name: Release Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: build
        run: |
          rm -f temporal-src-network.zip && \
          (cd src; zip -r ../temporal-src-network.zip *)

      - name: sha256sums
        run: |
          sha256sum temporal-src-network.zip > sha256sums.txt

      - name: Attach files to release
        env:
          RELEASE_TAG: ${{ steps.vars.outputs.tag }}
        run: >-
          hub release edit
          -m ""
          -a ./temporal-src-network.zip
          -a ./sha256sums.txt
          $RELEASE_TAG
